add range selection for datasets
SecurityLab-UCD/function-embedding pull request #19
Opened 2022-12-27 22:11 UTC by EYH0602

2022-12-27 22:26 UTC, DataCorrupted requested changes

2022-12-27 22:26 UTC, DataCorrupted commented on scripts/dataset.py
> +            unreachable("Invalid problem range")
`unreachable` is a strong guarantee that this will definitely not be executed. It is explicitly written to express that belief. (So in compiler's perspective this is basically useless)
This is not `unreachable` as users can provide invalid input, you can't guarantee on user's behavior.

It's would be more appropriate to use assertion or test then `logging.error()`.

2022-12-27 22:26 UTC, DataCorrupted commented on scripts/dataset.py
> +        self.problems = range(start, end + 1)
Not all problems are numeric. IBM uses format `p[0-9]*` which starts with a `p`. I think you want `self.problems = self.problems[range(...)]`, although this is matlab syntax, I am not sure if python supports this.

2022-12-27 22:26 UTC, DataCorrupted commented on scripts/dataset.py
> +        end = max(map(int, os.listdir(self.txtdir)))
1. could do this with `end = len(...)`.
2. Not all problems are numeric. IBM use p0000 to p9999.

2022-12-27 22:26 UTC, DataCorrupted commented on scripts/dataset.py
> +        assert start <= end
If assertion fails, provide a text string to tell the user why this doesn't work.

2022-12-27 22:26 UTC, DataCorrupted commented on scripts/dataset.py
> +            end = int(pr[1])
A easy (but not so secure) way is to directly `eval(problem_range)`. You can do a regex before to make sure the string only has numbers, comma and brackets so its safe.

2022-12-27 22:26 UTC, DataCorrupted commented on scripts/dataset.py
> +        default=":",
Default to `None` and only if it is not `None` do we `set_problems` so we don't call `set_problems` every time the script is run

2022-12-27 23:36 UTC, EYH0602 commented on scripts/dataset.py
> +            end = int(pr[1])
if `eval` failed, the program should stop anyway

2022-12-28 00:26 UTC, DataCorrupted commented on scripts/dataset.py
> +            end = int(pr[1])
That's two separate things:

1. If `eval` failed, we should try catch it and provide some feedback to the user
2. I am more worried about the user providing malicious code, say `"os.remove(`/`)"`. But let's not worry about it for now.

2022-12-28 00:29 UTC, DataCorrupted requested changes

2022-12-28 00:29 UTC, DataCorrupted commented on scripts/dataset.py
> +            max(pr) <= len(self.problems) and min(pr) >= 0
less than. equal than `self.problems` length may cause OOB below.

2022-12-28 00:29 UTC, DataCorrupted commented on scripts/dataset.py
> +        pr = eval(problem_range)
please try catch the `eval` and provide a feedback.

2022-12-28 00:29 UTC, DataCorrupted commented on scripts/dataset.py
> +            return
May want to move this check immediately after `eval` otherwise I am not sure if `None` can be `max`-ed and `min`-ed

2022-12-28 01:19 UTC, DataCorrupted approved these changes

2022-12-28 01:19 UTC, merged