Text replace scripts
SecurityLab-UCD/function-embedding pull request #4
Opened 2022-12-12 02:12 UTC by EYH0602

finished `scanf` and `cin` with return.
update text replacement script #3

2022-12-12 03:43 UTC, EYH0602 commented on encode2stderr.hpp
> +  }()\
need `{}` here

2022-12-12 04:31 UTC, DataCorrupted commented on encode2stderr.hpp
> +  } else {
I recommend `else if (... == 'd') {} else { unreachable; }` to make code more clear

2022-12-12 04:31 UTC, DataCorrupted commented on scripts/build.sh
> +            # TODO: check if file contains `gets()` then use --std=c++11
Didn't we default to C++11?

2022-12-12 05:21 UTC, EYH0602 commented on scripts/replace_input.py
> +    is_while_loop = "while" in tokens[0]
there are for loop also use `cin`

for example 1/1176
```cpp
for (cin >> n; n > 0; n--) 
// is replaced by
for (CIN(n; n--);
```

2022-12-12 20:56 UTC, EYH0602 commented on encode2stderr.hpp
> +#define SCANF_ALT(fmt, args...) scanf_alt(fmt, #args, args)
error if `scanf("\n");` with no other args

2022-12-13 00:54 UTC, DataCorrupted requested changes

2022-12-13 00:54 UTC, DataCorrupted commented on scripts/check_data_integrity.py
> +        else os.environ["EMBDING_HOME"] + "/output-1"
import common, `EMBDING_HOME`, and `CORES` can be directly used.

2022-12-13 00:54 UTC, DataCorrupted commented on encode2stderr.hpp
> +    std::cout << #x << ",," << x << "\n";                                      \
cerr

2022-12-13 00:54 UTC, DataCorrupted commented on encode2stderr.hpp
> +      std::cout << #x << ",," << x << "\n";                                    \
cerr

2022-12-13 00:54 UTC, DataCorrupted commented on encode2stderr.hpp
> +    // set default type to int
remove comments

2022-12-14 21:14 UTC, DataCorrupted approved these changes

2022-12-15 20:18 UTC, merged